language: python
sudo: false
python:
  - "2.7"
env:
  global:
    OUTPUT=www
    LIB_COPY=filelist.txt
    NO_DEFAULT=1
    NO_WEB=
    PUBLISH=1
script: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  ./create.sh
notifications:
  email:
    on_success: never
